### ISSUE TITLE
Can not login to confluence + pyyaml error

### ISSUE THREAD

**Issue by neomh** [atc-project/atomic-threat-coverage#146]
Hi

I'm getting this error when running docker :

docker run -it atc
[*] Setting up confluence
/app/scripts/atcutils.py:116: YAMLLoadWarning: calling yaml.load_all() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  buff_results = [x for x in yaml_fields]
Login: xxx
Password: xxxx
Creating ATC page..
Unauthorized Response. Try to use token instead of password 

I also tried using email / username from confluence with no luck

Please advise

Thank you

**Comment by yugoslavskiy** [comment]
Hello @neomh ,

have tried to use confluence API token instead of a password?

**Comment by neomh** [comment]
> Hello @neomh ,
> 
> have tried to use confluence API token instead of a password?

Hi @yugoslavskiy ! how can specify using the API key in the config file ?

**Comment by neomh** [comment]
resolved :)
