### ISSUE TITLE
Avoid rebuilding Confluence pages for files that were not modified

### ISSUE THREAD

**Issue by tr4cefl0w** [atc-project/atomic-threat-coverage#147]
This is a feature request, not really a bug.

Currently, when running make, the entire Confluence space is rebuilt, even for response actions, playbooks, detection rules and logging policies that were not modified. It takes a while. It would be nice to have Confluence pages update only for files that were modified, by keeping a hash table or whatever mean necessary.

I would also suggest using the atlassian-python-api package instead of doing manual calls to simplify the code but also because there are easy to use methods to update existing pages instead of recreating them (also can be done using the REST API directly).

**Comment by tr4cefl0w** [comment]
We use a self-hosted Confluence. If it's a bug I'll try to help and track down where the issue lies. I didn't dig any further than that. I'll get back to you here if I have time to check and find anything.

**Comment by mrblacyk** [comment]
I found the [https://github.com/atc-project/atomic-threat-coverage/blob/master/scripts/atcutils.py#L343](check) which fails to determine whether the page has the same content or not. 

I will try to fix it in upcoming days.

**Comment by yugoslavskiy** [comment]
'twas fixed in #164
