### ISSUE TITLE
Publishing to confluence not working

### ISSUE THREAD

**Issue by squ1ddy** [atc-project/atomic-threat-coverage#152]
Hello,

Receiving this error everytime the `docker run -it atc' command is run:
```
[*] Creating confluence repository and pushing data
Provide confluence credentials

Login: s*****@******.com.au
Password:
Creating ATC page..
Unauthorized Response. Try to use token instead of password
 https://developer.atlassian.com/cloud/confluence/basic-auth-for-rest-apis/#supplying-basic-auth-headers
[*] Creating elastic index
[-] Old atc_es_index.json has been deleted 
```

I've uploaded config.yml for reference.

Any help much appreciated,

[config.yml.txt](https://github.com/atc-project/atomic-threat-coverage/files/4008266/config.yml.txt)

**Comment by yugoslavskiy** [comment]
Hello @squ1ddy ! 

There was a similar issue #146 .
Have you tried to use API token instead of a password? 

Thanks, 
Dan

**Comment by yugoslavskiy** [comment]
I am closing issue due to absence of response for more than 30 days.
