### ISSUE TITLE
Fix logic of TG rendering in DR's `.md` template

### ISSUE THREAD

**Issue by yugoslavskiy** [atc-project/atomic-threat-coverage#162]
For some reason this line is working incorrectly:

https://github.com/atc-project/atomic-threat-coverage/blob/916b9db8b0a7c01c9784a7c1eecb9e0ebdfb41a5/scripts/templates/markdown_alert_template.md.j2#L7

It's broken in the way that even if there is no Trigger for some specific technique, ATC adds (renders) a link to it (links not-existing file) in a DR markdown file. 

Need to fix and rebuild markdown DRs.

**Comment by sn0w0tter** [comment]
fixed in 9f9670ac9d94845e293f1c09b280ed424716e7dd
