### ISSUE TITLE
Develop LP for PS Event ID 4104 and 4103

### ISSUE THREAD

**Issue by yugoslavskiy** [atc-project/atomic-threat-coverage#172]
There is a couple of DNs (the most critical ones) without LP developed:

* [DN_0036_4104_windows_powershell_script_block](https://github.com/atc-project/atomic-threat-coverage/blob/master/data_needed/DN_0036_4104_windows_powershell_script_block.yml)

* [DN_0037_4103_windows_powershell_executing_pipeline](https://github.com/atc-project/atomic-threat-coverage/blob/master/data_needed/DN_0037_4103_windows_powershell_executing_pipeline.yml)

We need to have these LP developed, using [LP template](https://github.com/atc-project/atomic-threat-coverage/blob/master/logging_policies/loggingpolicy.yml.template).

**Comment by sn0w0tter** [comment]
Added in 26d7021f1dcd8a58cf885182dc863743eb7ee55b
