### ISSUE TITLE
Confluence dependency

### ISSUE THREAD

**Issue by idev** [atc-project/atomic-threat-coverage#199]
Hello,

first: great and interesting project!

But I see the dependency to other Tools like Confluence critical regarding usablity for a broad community.

I can only speak for myself, but I do not have access to a Confluence and Kibana environment.

Kind regards

**Comment by mrblacyk** [comment]
Hey @idev!

You can use any tool which translates markdown into HTML files or build one yourself. What I have researched and tested myself, [mkdocs](https://www.mkdocs.org/) gives similar to the Confluence experience. Just..

- Generate markdown files.
- Generate new mkdocs project.
- Copy all the directories containing markdown files into the `docs` directory of the mkdocs project.
- Issue `mkdocs serve` from within mkdocs project dir.
- Visit http://127.0.0.1:8000/
- Profit

We are planning a video to give step-by-step guide on how to do it but those above are the most important steps of the process.

Elastic offers community version of their products - meaning they're free of charge to use. They also keep up to date images on Docker Hub which comes handy in just a sec. If this is just for evaluating the project, you can always spin up couple of containers and setting up ELK Stack on your machine. You can do it by hand or use [docker-compose docker-elk project](https://github.com/deviantony/docker-elk/blob/master/docker-compose.yml) for that.

Hope that this keeps you going with ATC!

I'm going to close the issue in 7 days but should you have any more questions, please put them here and we will continue. 

Cheers!
@mrblacyk

**Comment by idev** [comment]
Thank you, great response!
