### ISSUE TITLE
Multiple outputs

### ISSUE THREAD

**Issue by golaso** [atc-project/atomic-threat-coverage#200]
Guys, you have added multiple outputs like es-qs, splunk and others for detection rules in [markdown format](https://github.com/atc-project/atomic-threat-coverage/blob/62ff711b16713a70bb70dd76e6b152348e47e614/scripts/detectionrule.py#L77), but did not add these outputs for [confluence format](https://github.com/atc-project/atomic-threat-coverage/blob/62ff711b16713a70bb70dd76e6b152348e47e614/scripts/detectionrule.py#L229)

**Comment by sn0w0tter** [comment]
Hi @golaso,
Multiple outputs are supported for both platform, it is configurable in config.
Part of the code witch you spotted is responsible for loading configuration for specific backend. This feature (#192) is still in develop branch, but it was implemented for both platforms.
