### ISSUE TITLE
Wrong name for files DN_0044_1000_application_crashed.yaml  DN_0045_1001_windows_error_reporting.yaml

### ISSUE THREAD

**Issue by LouDeter** [atc-project/atomic-threat-coverage#202]
Files DN_0044_1000_application_crashed.yaml  and DN_0045_1001_windows_error_reporting.yaml are named XX.y**a**ml instead of xx.yml and are not parsed in the data needed evaluation process.

**Comment by sn0w0tter** [comment]
Hi @LouDeter,
Thanks for spotting this. I fixed the extensions.
