### ISSUE TITLE
Web application

### ISSUE THREAD

**Issue by rashimo** [atc-project/atomic-threat-coverage#205]
Hi,

I really like the project. I was wondering how are the plans regarding the Web application which was mentioned in the Bsides Singapore 2019 presentation? And also what features are planed in the app. 

Best Regard

**Comment by yugoslavskiy** [comment]
Hello @rashimo! 

Thank you for your interest in the project!
Everything is quite complicated at the moment.
There were many urgent tasks in the queue — the RE&CT release, splitting the main project into submodules, modifying schema for Data Needed / Logging Policies / Enrichments. 
At the same time, we were organizing OSCD sprints, and it also took lots of time and effort. 

I believe that we will finish most of these urgent tasks in the upcoming weeks and get back to the new WEB IU.
@mrblacyk can tell you more about it, as he is the developer of Django API that will play the role of a backend in the future WEB UI.

**Comment by rashimo** [comment]
Thank you @yugoslavskiy for your informative reply. Can't wait to here more good new.
