### ISSUE TITLE
Inconsistency in es_index_export.py and config file

### ISSUE THREAD

**Issue by andrazjelenc** [atc-project/atomic-threat-coverage#215]
Hi guys.

In **es_index_export.py** in **line 30** we load enrichments directory from config:
`en_path = ATCconfig.get('enrichments_directory')`

But in config file enrichments directory is defined **as enrichments_dir, not enrichments_directory**.

Therefore loading enrichments directory fails.

**Comment by yugoslavskiy** [comment]
Hello @andrazjelenc! 
Thank you very much for your help! 
Will fix it in a few minutes (:
