### ISSUE TITLE
ValueError tactic_refs

### ISSUE THREAD

**Issue by wbnod** [atc-project/atomic-threat-coverage#226]
When trying to run ATC from a fresh git clone / edit config.yml / docker build . -t atc / docker run -it atc, then it throws an error for each step in docker-entrypoint.sh and docker exits prematurely.

`ValueError: 'tactic_refs' is named like a reference list property but is not a 'ListProperty' containing a subclass of 'ReferenceProperty'.
`
See attached screen shot of traceback: main.py > react2stix.py > sdo.py > custom.py > registration.py (in stix2 library).
![image](https://user-images.githubusercontent.com/56418809/136454227-d7c87146-d323-4a9d-80ba-0002171df90d.png)

**Comment by wbnod** [comment]
These were also run prior to the docker build:
git submodule init
git submodule update
git submodule foreach git pull origin master

**Comment by yugoslavskiy** [comment]
Thank you very much for your issue, @wbnod! 
Issue has been resolved with @xofolowski [assistance](https://github.com/atc-project/atc-react/issues/361).
Have a great weekend, guys!
